### ISSUE TITLE
Crash at reader audio player

### ISSUE THREAD

**Issue by ProudOfZiggy** [FolioReader/FolioReaderKit#115]
First of all thank you for epub3.0 support.

I just opened this book and closer reader.
https://www.dropbox.com/s/4c71odxfs6yrcsg/multimedia-remix-2.epub?dl=0

It crashed at FolioReaderKit.swift (197):
FolioReader.sharedInstance.readerAudioPlayer.stop(immediate: true)

**Comment by hebertialmeida** [comment]
Hey @ProudOfZiggy please try again that on last master, I think it is already fixed because I am testing and working normal for me.

**Comment by hebertialmeida** [comment]
I have pushed the last version to Cocoapods

**Comment by ProudOfZiggy** [comment]
Updated pod 'FolioReaderKit', '~> 0.8'
But still crashing for me... I just open book I provided to you and close it

**Comment by ProudOfZiggy** [comment]
Ok, I found it.
It crashing with: "fatal error: unexpectedly found nil while unwrapping an Optional value" on this line FolioReaderKit.swift (197):

FolioReader.sharedInstance.readerAudioPlayer.stop(immediate: true) 

because readerAudioPlayer is nil.

http://joxi.ru/Dr8K4XpsE3qLA6

Why you made this one 'weak'?

**Comment by hebertialmeida** [comment]
I just run the book you send and it works nice using 0.8.4, so I can't simulate that.
Yeah you are right this needs to be optional, needs some refactor, does it fix for you? 
I am working another feature now, I but when I finish this I can take a look.

**Comment by hebertialmeida** [comment]
I think I know what is that, do you set `enableTTS = false`?

**Comment by hebertialmeida** [comment]
Fixed that, I will release it ASAP.

**Comment by ProudOfZiggy** [comment]
Nope, never used enableTTS

**Comment by hebertialmeida** [comment]
Have you tested 0.8.6?

**Comment by ProudOfZiggy** [comment]
Yep, just tested. Not crashing anymore, thank you. I'll continue my tests. Will tell you if I found something else.
