### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set

### ISSUE THREAD

**Issue by onivem** [FolioReader/FolioReaderKit#308]
Hey, I'm getting the following error:
**The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.**

for couple of pods FolioReaderKit is using:
**AEXML,
MenuItemKit,
JSQWebViewController,
FontBlaster**

It's possible to fix issue by providing setting SWIFT_VERSION setting for each target. While after pod install this setting will reset.

I'm trying to integrate FolioReaderKit into Objective-C only project. 
Xcode version I'm using - 9.2
CocoaPods - 1.4.0

**Comment by tschob** [comment]
Hey. CocoaPods 1.4.0 introduced a new way to specify the Swift version of a Pod. Instead of declaring it in the *.swift_version* file it has to be done in the *podspec* as `spec.swift_version` now. These changes have to be done in libraries.

But, you can change these build settings automatically anyway. Add the following code snippet to your Podfile to change the Swift version of a Pod:

```ruby
post_install do |installer|

	swift4Targets = ['FolioReaderKit'] # Specify Pods which are Swift 4 here

	installer.pods_project.targets.each do |target|

		target.build_configurations.each do |config|

			if swift4Targets.include? target.name
				config.build_settings['SWIFT_VERSION'] = '4.0'
			else
				config.build_settings['SWIFT_VERSION'] = '3.2'
			end
		end
	end
end
```

**Comment by iCodist** [comment]
After I pod FolioReaderKit，I found its code isn't Swift 4, I don't know why. My Xcode is 9.2, CocoaPods is 1.4.0.

**Comment by hebertialmeida** [comment]
Is it fixed by #309?

**Comment by onivem** [comment]
@hebertialmeida The issue still present in FolioReaderKit 1.2.0
While, as far as I see - issue is not with FolioReaderKit, but with it's dependancies:
**AEXML,
MenuItemKit,
JSQWebViewController,
FontBlaster**

**Comment by tschob** [comment]
@hebertialmeida The issue is fixed for FolioReakderKit iself, but not for its dependencies. These have to provide versions which are build with CocoaPods 1.4.0 to make the workaround unnecessary.

**Comment by hebertialmeida** [comment]
I will close this since it seems that it is not on us.
