### ISSUE TITLE
Nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by afornes** [FolioReader/FolioReaderKit#64]
I installed FolioReaderKit using pods on my project but I still didn't used it. Only installation. After that, my app ran perfectly. Now, I've embedded my main controller into a navigation controller and now my app crashed when executed. This is the error I'm getting:

fatal error: unexpectedly found nil while unwrapping an Optional value
![captura de pantalla 2016-04-29 a las 13 42 11](https://cloud.githubusercontent.com/assets/5265197/14915150/c9cf77ca-0e10-11e6-87c0-924cd52e3ced.png)

**Comment by hebertialmeida** [comment]
I have just released a fix for this, please update it and let me know.

**Comment by afornes** [comment]
I've updated the pod and I'm still having the same problem.
I patched it by changing this:
`get { return FolioReader.defaults.valueForKey(kNightMode) as! Bool }`
for this:
`get { return FolioReader.defaults.boolForKey(kNightMode) }`

**Comment by hebertialmeida** [comment]
Can you make a Pull Request with this?

**Comment by afornes** [comment]
Sure!

**Comment by afornes** [comment]
I'm trying to make the Pull Request but I'm getting this error:
`You may not have permission to access FolioReaderKit. Check Preferences to make sure you’re still logged in.`
